General:
  BATCH_SIZE: 256
  IMAGE_SIZE: 32
  SEED: 69

Testing:
  BATCH_SIZE: 1000
  LR_CLASSIFIER: 0.001
  NUM_ITERS: 100
  NUM_EPOCHS: 2
  SEEDS: [1, 2, 3]
  SPEED_RUNS: 10
  SPEED_SAMPLES: 1000
  SPEED_MAX: 3

Hyperparameters:
  LR_GEN: 0.003
  LR_DISC: 0.003
  BETAS_ADAM_GEN: [0.5, 0.999]
  BETAS_ADAM_DISC: [0.5, 0.999]
  NUM_EPOCHS: 100
  CONV_DIM: 64
  Z_DIM: 10
  EMBED_SIZE: 5

Weights:
  SAVE_WEIGHTS_PATH: 'weights/latent_10_embed_5/'
  LOAD_WEIGHTS_PATH: 'weights/latent_10_embed_5/checkpoint_epoch_89.pth'